FROM docker.io/rust:1.56.1-alpine3.13 as BUILDER

WORKDIR /app

RUN apk add musl-dev libc-dev postgresql-dev

RUN cargo install diesel_cli --no-default-features --features "postgres"

FROM gcr.io/distroless/cc

WORKDIR /app

ADD migrations/ /app/migrations/

COPY --from=BUILDER /usr/local/cargo/bin/diesel .

CMD ["/app/diesel", "migration", "run"]
