FROM docker.io/rust:1.56 as BUILDER

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev
RUN rustup default nightly

ADD . .

RUN --mount=type=cache,target=/app/target cargo build --release && cp /app/target/release/thirsty-broker /app/thirsty-broker

FROM docker.io/debian:11-slim

RUN apt-get update && apt-get install -y libpq5

WORKDIR /app

COPY --from=BUILDER /app/thirsty-broker .

CMD ["/app/thirsty-broker"]
